version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${DB_DATABASE_NAME}"
      - "SPRING_DATASOURCE_USERNAME=${DB_USER}"
      - "SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
